#!/usr/bin/env bash

cd ..

mkdir -p Assembly

echo "#pragma once" > Source/Configuration.h
echo "#define LINUX" >> Source/Configuration.h
#echo "#define DEBUG" >> Source/Configuration.h

file=${PWD##*/}_$(basename $0).asm

clang++ -S -g -Wall -std=c++17 Source/*.cpp -o Assembly/$file