#!/usr/bin/env bash

cd ..

mkdir -p Binaries

echo "#pragma once" > Source/Configuration.h
echo "#define LINUX" >> Source/Configuration.h

file=${PWD##*/}_$(basename $0)

clang++ -O3 -std=c++17 Source/*.cpp -o Binaries/$file

./Binaries/$file